name: "Production Build"

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]
  workflow_dispatch:

jobs:

  Frontend:

    runs-on: ubuntu-latest

    environment:
      name: Production

    strategy:
      matrix:
        node-version: ["18.x"]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd react-frontend
        npm ci

    # - name: Test
    #   run: npm test

    - name: Build 
      run: |
        cd react-frontend
        npm run build --if-present
